admitad/admin/forms.py
from flask_wtf import Form
from wtforms import (StringField, SubmitField, HiddenField,
                     BooleanField, SelectField, IntegerField,
                     validators as v, ValidationError)


class SetupForm(Form):
    website_id = StringField('ID сайта',
                             validators=[v.data_required('Нужно указать ID сайта в Адмитаде')])
    submit = SubmitField('Добавить')

    def validate_website_id(form, field):
        if not field.data.isdigit():
            raise ValidationError('Должны быть только цифры')


class ProgramCategoryForm(Form):
    copy = BooleanField('Копировать', validators=[v.Optional()])
    copy_to = SelectField('в категорию', default='__None',
                          choices=[('__None', 'Каталог')],
                          validators=[v.Optional()])
    submit = SubmitField('Сохранить')

    def validate_copy_to(form, field):
        if field.data == '__None':
            field.data = None


class AddCategoryForm(Form):
    name = StringField('Название', validators=[
        v.DataRequired('Название обязательно'),
        v.Length(min=3, max=200, message='Длина должна быть между %(min)d и %(max)d символами')
    ])
    slug = StringField('Ссылка', validators=[v.Optional()])
    parent = SelectField('Родитель', choices=[('__None', 'Нет родителя')],
                         default='__None', validators=[v.Optional()])

    def validate_parent(form, field):
        if field.data == '__None':
            field.data = None
        else:
            try:
                field.data = int(field.data)
            except ValueError:
                raise ValidationError('Неправильный выбор')


class EditCategoryForm(AddCategoryForm):
    position = IntegerField('Позиция', default=0, validators=[v.Optional()])


class AddFilterGroupForm(Form):
    name = StringField('Название', validators=[
        v.DataRequired('Название обязательно'),
        v.Length(min=3, max=100, message='Длина должна быть между %(min)d и %(max)d символами')
    ])
    slug = StringField('Ссылка', validators=[v.Optional()])


class AddFilterForm(Form):
    name = StringField('Название', validators=[
        v.DataRequired('Название обязательно'),
        v.Length(min=3, max=100, message='Длина должна быть между %(min)d и %(max)d символами')
    ])
    name_kind = StringField('«Какие»', validators=[
        v.Optional(),
        #v.DataRequired('Обязательно, нужно для заголовков'),
        v.Length(min=3, max=100, message='Длина должна быть между %(min)d и %(max)d символами')
    ])
    slug = StringField('Ссылка', validators=[v.Optional()])
    group = SelectField('Группа', choices=[], validators=[
        v.DataRequired('Группа обязательна')
    ])

admitad/__init__.py
from .app import create_app
from .ext import celery

app = create_app()

admitad/admin/__init__.py
from flask import Blueprint, g
from admitad.settings import Config
from .models import AdminSettings

admin = Blueprint('admin', __name__,
                  url_prefix=getattr(Config, 'ADMIN_URL_PREFIX', '/admin'),
                  template_folder='templates/')


from .views import *


admin.add_url_rule('/', view_func=IndexView.as_view('index'))
admin.add_url_rule('/123/', view_func=IndexView.as_view('index.uri'))

admin.add_url_rule('/setup/', view_func=SetupView.as_view('setup'))

# Programs
admin.add_url_rule('/programs/',
                   view_func=ProgramsView.as_view('programs'))
admin.add_url_rule('/programs/<int:pid>/',
                   view_func=ProgramCategoriesView.as_view('programs.item'))
admin.add_url_rule('/programs/<int:pid>/<cid>/',
                   view_func=ProgramCategoriesView.as_view('programs.item.view'))


# Catalog
admin.add_url_rule('/catalog/offers/',
                   view_func=CatalogView.as_view('catalog'))
admin.add_url_rule('/catalog/offers/<category_id>/',
                   view_func=CatalogView.as_view('catalog.category'))
admin.add_url_rule('/catalog/categories/',
                   view_func=CatalogCategoryView.as_view('categories'))
admin.add_url_rule('/catalog/categories/<category_id>/',
                   view_func=CatalogCategoryView.as_view('categories.edit'))
admin.add_url_rule('/catalog/categories/<category_id>/delete/',
                   view_func=CatalogCategoryView.as_view('categories.delete'))
admin.add_url_rule('/catalog/shops/',
                   view_func=CatalogShopView.as_view('shops'))
admin.add_url_rule('/catalog/brands/',
                   view_func=CatalogBrandView.as_view('brands'))
admin.add_url_rule('/catalog/filters/',
                   view_func=CatalogFiltersView.as_view('filters'))
admin.add_url_rule('/catalog/filters/<group_slug>/',
                   view_func=CatalogFiltersView.as_view('filters.group'))


# Filler
admin.add_url_rule('/filler/', view_func=FillerView.as_view('filler'))


# API
admin.add_url_rule('/api/get_task_result/',
                   view_func=get_task_result, methods=['POST'])
admin.add_url_rule('/api/toggle_program/',
                   view_func=toggle_program, methods=['POST'])
admin.add_url_rule('/api/toggle_program_parse/',
                   view_func=toggle_program_parse, methods=['POST'])
admin.add_url_rule('/api/get_offers_examples/',
                   view_func=get_offers_examples, methods=['POST'])
admin.add_url_rule('/api/get_offer_examples/',
                   view_func=get_offer_example, methods=['POST'])

admin.add_url_rule('/api/reupload_image/<offer_id>/',
                   view_func=reupload_image)

admin.add_url_rule('/api/disable_offer/<offer_id>/',
                   view_func=disable_offer)


# Pages
admin.add_url_rule('/pages/', view_func=PagesView.as_view('pages'))
admin.add_url_rule('/pages/create/', view_func=PagesView.as_view('pages.item.create'))
admin.add_url_rule('/pages/<id>/', view_func=PagesView.as_view('pages.item'))
admin.add_url_rule('/pages/<id>/delete/', view_func=PagesView.as_view('pages.item.delete'))


from flask import render_template
from .decorators import admin_required
from .models import UserFill, User, Offer

@admin.route('/stats/')
@admin_required
def users_stats():
    fills = UserFill.objects(stats__total__gt=0)
    user_ids = fills.distinct('user_id')
    users = {user.id: user for user in User.objects(id__in=user_ids)}
    return render_template('admin/user_stats.html',
                           fills=fills,
                           users=users,
                           total_offers=Offer.available().count())

admitad/admin/views/__init__.py
from .api import (get_task_result, toggle_program,
                  get_offers_examples, get_offer_example,
                  reupload_image, disable_offer, toggle_program_parse)

from .index import IndexView
from .setup import SetupView
from .program import ProgramsView, ProgramCategoriesView
from .catalog import (CatalogView, CatalogCategoryView,
                      CatalogBrandView, CatalogShopView,
                      CatalogFiltersView)

from .filler import (FillerView, )
from .pages import PagesView

admitad/admin/views/api.py
from flask import request, jsonify, render_template

from admitad.ext import celery

from .mixins import admin_required
from ..models import Program, ProgramOffer
from ..feed_parse import parse
from ..tasks import download_image

from admitad.modules.catalog.models import Offer


@admin_required
def get_task_result():
    task_id = request.form.get('task_id')
    if task_id:
        return celery.AsyncResult(task_id).ready()
    return True


@admin_required
def toggle_program():
    pid = request.form.get('pid')
    assert pid and str(pid).isdigit()
    program = Program.get_by_id(pid)
    program.toogle_enabled()
    Offer.objects(reference__istartswith=str(program.id) + '-')\
         .update(set__is_enabled=program.is_enabled)
    return jsonify(result=True)


@admin_required
def toggle_program_parse():
    pid = request.form.get('pid')
    assert pid and str(pid).isdigit()
    program = Program.get_by_id(pid)
    if program.is_active and program.is_enabled:
        program.parse_by_keywords = not program.parse_by_keywords \
            if program.parse_by_keywords else True
    else:
        program.parse_by_keywords = False
    program.save()
    return jsonify(result=True)


@admin_required
def get_offers_examples():
    program_id = request.form.get('program_id')
    if not program_id:
        return
    program = Program.get_by_id(program_id)
    examples = parse(program.xml_file, adapter='offer', tag='offer',
                     parent='offers', live=True, limit=50,
                     cid=request.form.get('category_id', None))
    return jsonify(result=examples)


@admin_required
def get_offer_example():
    offer_id = request.form.get('offer_id')
    if not offer_id:
        return
    offer = ProgramOffer.objects.get(id=offer_id)
    html = render_template('admin/program/offer.html', offer=offer)
    return jsonify(result=html)


@admin_required
def reupload_image(offer_id):
    offer = Offer.objects(id=offer_id).first()
    if not offer:
        return
    download_image.delay(offer)
    return jsonify(result=True)


@admin_required
def disable_offer():
    offer_id = request.form.get('offer_id')
    if not offer_id:
        return

admitad/admin/views/catalog.py
from flask import request, redirect, render_template, url_for

from .mixins import AdminViewMixin
from ..forms import (AddCategoryForm, EditCategoryForm,
                     AddFilterGroupForm, AddFilterForm)

from admitad.modules.catalog.models import (Category, Offer,
                                            Shop, FilterGroup, Filter)

from admitad.modules.catalog.models.filters import EmbbedFilterGroup


class CatalogView(AdminViewMixin):

    def get(self, category_id=None):
        categories, current = Category.get_tree(category_id, True)
        offers = Offer.objects.only('name', 'url', 'pictures',
                                    'price', 'old_price', 'discount')

        filters = {}
        filters_groups = FilterGroup.objects.distinct('slug')
        match = []
        facets = {}

        if category_id:
            filters['category__path__istartswith'] = current.path

        for key, value in request.args.items():
            if key in ('shop', 'brand'):
                filters['{key}__slug'.format(key=key)] = value

            if key in filters_groups:
                if not filters.get('facets__all'):
                    filters['facets__all'] = []
                filters['facets__all'].append(':'.join([key, value]))


        if 'available' in request.args:
            filters['is_available'] = False


        # searches = {}
        # for f in offers.distinct('facets'):
        #     group, value = f.split(':')
        #     searches.setdefault(group, []).append(value)

        sort = request.args.get('sort')
        if sort:
            offers = offers.order_by(sort)

        page = request.args.get('page', 1)
        try:
            page = int(page)
        except ValueError:
            page = 1

        offers = offers.filter(**filters)
        filters = FilterGroup.get_dict(facets=list(filter(None, offers.distinct('facets'))))
        offers = offers.paginate(per_page=40, page=page)

        return render_template('admin/catalog/main.html',
                               categories=categories,
                               category=current,
                               offers=offers,
                               filters=filters,
                               shops=Shop.objects.only('name', 'slug'),
                               brands=[])


class CatalogCategoryView(AdminViewMixin):
    template = 'admin/catalog/categories.html'

    def get_context(self, category_id):
        categories = Category.get_tree()
        context = {}

        if not category_id:
            category = Category()
            form = AddCategoryForm(request.form)
            form.parent.choices = form.parent.choices.copy() + \
                                  [c for c in Category.flat_from_tree(categories)]
            context['categories'] = categories
        else:
            category = Category.objects.get_or_404(id=category_id)
            form = EditCategoryForm(request.form, obj=category)
            form.parent.choices = form.parent.choices.copy() + \
                                  [c for c in Category.flat_from_tree(categories,
                                                                      category_id)]

        context.update({'form': form,
                        'category': category})

        return context

    def get(self, category_id=None):
        context = self.get_context(category_id)

        if request.endpoint == 'admin.categories.delete':
            context.get('category').delete()
            return redirect(url_for('admin.categories'))

        return render_template(self.template, **context)

    def post(self, category_id=None):
        context = self.get_context(category_id)
        form = context.get('form')
        category = context.get('category')
        if form and form.validate_on_submit():
            form.populate_obj(category)
            category.save()
            return redirect(url_for('admin.categories'))
        return render_template(self.template, **context)


class CatalogFiltersView(AdminViewMixin):
    template = 'admin/catalog/filters.html'
    forms = {
        'group_form': AddFilterGroupForm,
        'filter_form': AddFilterForm,
    }

    def get_context(self, group_slug, id):
        context = {}

        groups = FilterGroup.objects

        context['groups'] = groups
        context['group_form'] = self.forms.get('group_form')(request.form)

        filter_form = self.forms.get('filter_form')(request.form)
        filter_form.group.choices = [(str(gr.id), gr.name,) for gr in groups]

        filters = Filter.objects

        if group_slug:
            current_group = groups.get_or_404(slug=group_slug)
            filter_form.group.data = str(current_group.id)
            filters = filters.filter(group__id=current_group.id)
            context['current_group'] = current_group

        context['filters'] = filters
        context['filter_form'] = filter_form

        return context

    def get(self, group_slug=None, id=None):
        context = self.get_context(group_slug, id)
        return render_template(self.template, **context)

    def post(self, group_slug=None, id=None):
        context = self.get_context(group_slug, id)
        group_form = context.get('group_form')
        filter_form = context.get('filter_form')

        if group_slug is None and group_form.validate_on_submit():
            group = FilterGroup()
            group_form.populate_obj(group)
            group.save()
            return redirect(url_for('admin.filters'))

        elif filter_form.validate_on_submit():
            current_group = context.get('current_group')

            filt = Filter()
            filter_form.populate_obj(filt)
            filt.group = EmbbedFilterGroup(**current_group.to_filter())
            filt.save()

            return redirect(url_for('admin.filters.group',
                                    group_slug=current_group.slug))

        return render_template(self.template, **context)


class CatalogShopView(AdminViewMixin):
    template = 'admin/catalog/shops.html'

    def get(self):
        return render_template(self.template)


class CatalogBrandView(AdminViewMixin):
    template = 'admin/catalog/brands.html'

    def get(self):
        return render_template(self.template)

admitad/admin/views/filler.py
import random

from flask import render_template, request, redirect, url_for
from flask_login import current_user

from .mixins import AdminViewMixin

from ..models import UserFill
from admitad.modules.catalog.models import (Filter, FilterGroup, Offer)


class FillerView(AdminViewMixin):
    template = 'admin/filler/index.html'

    def get(self):
        groups = FilterGroup.get_dict()
        offer_id = request.args.get('id', None)

        context = {
            'groups': groups,
        }

        if not offer_id:
            ids = Offer.not_filled().distinct('id')
            not_filled_count = len(ids)
            offer_id = random.choice(ids)
            context.update(not_filled_count=not_filled_count)
        offer = Offer.objects.get(id=offer_id) if offer_id else None

        fill = UserFill.get(current_user.id)

        context.update(offer=offer, fill=fill)

        return render_template(self.template, **context)

    def post(self):
        form = dict(request.form)
        offer_id = form.pop('offer_id', None)[0]

        keys = list(form.keys())
        is_skipping = False
        if 'skip_offer' in keys:
            keys.pop(keys.index('skip_offer'))
            is_skipping = True

        if len(keys) and offer_id and not is_skipping:
            offer = Offer.objects.get(id=offer_id)
            filters = Filter.objects(id__in=[i for i in form.keys()])
            facets = [filter.make_facete() for filter in filters]

            if not offer.status.is_filled:
                fill = UserFill.create_or_update(current_user.id)
                fill.set_filled_offer(offer)

            offer.update(set__facets=facets,
                         set__status__is_filled=True)


        return redirect(url_for('admin.filler'))

admitad/admin/views/index.py
from flask import render_template

from .mixins import AdminViewMixin

class IndexView(AdminViewMixin):
    template = 'admin/base.html'

    def get(self):
        return render_template(self.template)

admitad/admin/views/mixins.py
from flask.views import MethodView

from ..decorators import admin_required, settings_required


class AdminViewMixin(MethodView):
    decorators = [settings_required, admin_required]

admitad/templates/brands.html
{% extends 'base.html' %}

{% block content %}
    <div class="content__title">
        <h1>
            Бренды
        </h1>
        <span class="content__title-count">{{ total_brands }}</span>
    </div>

    <div class="brands">
    {% for group, brands in grouped_brands.items() %}
        <div class="brands__group">
            <div class="brands__group-letter">{{ group }}</div>
            <ul class="brands__list">
                {% for brand, count in brands %}
                <li class="brands__list-item">
                    <a href="{{ url_for('site.catalog', brand=brand.slug) }}" class="link-text link-normal">{{ brand.name|safe }} <span class="brands__list-count">{{ count }}</span></a>
                </li>
                {% endfor %}
            </ul>
        </div>
    {% endfor %}
    </div>

{% endblock %}

admitad/templates/favorites.html
{% from 'helpers/offers.html' import render_offer with context %}
{% from 'helpers/pagination.html' import render_pagination %}

{% extends 'base.html' %}

{% block content %}
    <div class="content__title">
        <h1>Отложенные модели</h1>
        {% if offers.total %}<span class="content__title-count">{{ offers.total|get_plural(['модель', 'модели', 'моделей']) }}</span>{% endif %}
    </div>

    {% if offers.total %}
    <ul class="offers offers--wide">
        {% for offer in offers.items %}
        {{ render_offer(offer) }}
        {% endfor %}
    </ul>
    {% if offers.pages > 1 %}
    <div class="pagination">
        {{ render_pagination(offers, path=current_path, **request.args) }}
    </div>
    {% endif %}
    {% else %}
    К сожалению нет товаров
    {% endif %}
{% endblock %}

admitad/templates/offer.html
{% from 'helpers/offers.html' import render_offer with context %}
{% from 'helpers/share.html' import render_share with context %}

{% extends 'base.html' %}

{% set altitle = 'Ботильоны' %}
{% if offer.brand %}
    {% set altitle = altitle + ' ' + offer.brand.name %}
{% endif %}

{% set redirect_link = offer.id|make_offer_redirect_url %}

{% block title %}
    {{ altitle }} за {{ offer.price|pretty_price }} руб. | {{ super() }}
{% endblock %}

{% set description = altitle %}
{% set df = {'color': None, 'heel': None} %}

{% if offer_filters %}
    {% for _, f in offer_filters.items() %}
        {% if f.get('filters', [])|length %}
            {% if f.get('slug') == 'color' %}
                {% do df.update({'color': f.get('filters')[0].name}) %}
            {% elif f.get('slug') == 'heel' %}
                {% do df.update({'heel': f.get('filters')[0].name}) %}
            {% endif %}
        {% endif %}
        {{ color }}
    {% endfor %}
{% endif %}

{% if df.get('color') %}
    {% set description = df.get('color')|capitalize + ' ' + description %}
{% endif %}

{% if df.get('heel') %}
    {% set description = description + ' ' + df.get('heel') %}
{% endif %}


{% block description %}
    {{ description }} в наличии всего за {{ offer.price|pretty_price }} руб. И еще более 7000 моделей обуви в продаже. Заказывайте!
{% endblock %}

{% block metas %}
<meta property="og:title" content="{{ altitle }}">
<meta property="og:description" content="{{ altitle }} всего за {{ offer.price|pretty_price }} руб. и другие модели ботильонов в интернет-магазине www.Botiloni.ru.">
<meta property="og:image" content="{{ offer.picture_absolute_path }}">
<meta property="og:type" content="website">
<meta property="og:url" content="{{ request.url }}">
{% endblock %}


{% block content %}
    <div class="content">
        <div class="content__wrapper" itemscope itemtype="http://schema.org/Product">
            <div class="content__right">
                {% if current_user and current_user.is_admin %}
                    <a href="{{ url_for('admin.reupload_image', offer_id=offer.id) }}" class="js-reupload-image">Перезагрузить картинку</a>
                {% endif %}
                {% if offer.discount %}
                <div class="offers__item-discount content__right-discount">–{{ offer.discount }}%</div>
                {% endif %}
                <a href="{{ redirect_link }}" target="_blank" class="link-normal">
                    <img src="{{ offer.picture }}"
                         itemprop="image"
                         alt="{{ altitle }}" title="{{ altitle }} всего за {% if offer.old_price %}{{ offer.old_price|pretty_price }}{% else %}{{ offer.price|pretty_price }}{% endif %} руб.">
                </a>
            </div>
            <div class="content__left">
                <div class="content__title">
                    <h1 itemprop="name"><span class="content__title-top">{{ site_name }}</span>
                    {% if offer.brand %}
                    <a href="{{ url_for('site.catalog', brand=offer.brand.slug) }}" class="link-text link-normal content__title-link">{{ offer.brand.name|safe }}</a>
                    {% endif %}</h1>
                    <meta itemprop="description" content="{% if offer.description %}{{ offer.description|striptags|safe }}{% else %}{{ altitle }}{% endif %}">
{#                    <div style="display: none" itemprop="description">#}
{#                        {{ offer.description|striptags|safe }}#}
{#                        <span class="link link-grey content__text-more">Читать полностью</span>#}
{#                    </div>#}
                </div>
                <div itemprop="offers" itemscope itemtype="http://schema.org/Offer">
                    <div class="offers__item-price content__offer-price">
                        <span class="offers__item-price-current">
                            <span itemprop="price" content="{{ offer.price }}">{{ offer.price|pretty_price }}</span> руб.
                        </span>
                        {% if offer.old_price %}<span class="offers__item-price-old">{{ offer.old_price|pretty_price }}</span>{% endif %}
                        <meta itemprop="priceCurrency" content="RUB">
                        <link itemprop="availability" href="http://schema.org/InStock">
                    </div>
                    {% set sizes = offer.get_sizes %}
                    {% if sizes %}
                    <div class="content__sizes">
                        Размер{% if sizes|length > 1 %}ы{% endif %} в наличии:
                        <ul class="content__sizes-list">
                            {% for size in sizes %}
                            <li class="content__sizes-item"><a href="{{ redirect_link }}" target="_blank" class="content__sizes-link">{{ size }}</a></li>
                            {% endfor %}
                        </ul>
                    </div>
                    {% endif %}
                    <div class="content__offer-buttons">
                        <noindex><a href="{{ redirect_link }}" target="_blank" rel="nofollow" class="btn btn--big btn--buy">Купить в магазине</a></noindex>
                        &nbsp;&nbsp;
                        <a href="{{ url_for('site.favorites', id=offer.id) }}" class="offers__item-add-to-favorites{% if offer.in_favorites %} offers__item-add-to-favorites--added{% endif %} content__offer-favorite">
                            <svg class="icon">
                                <use xlink:href="#icon-favorite"></use>
                            </svg>
                        </a>
                    </div>
                    {% if offer.description %}
                    <div class="content__offer-description">
                        <h4>Описание</h4>
                        <div class="content__offer-description-text" itemprop="description">
                            {{ offer.description|striptags|safe }}
    {#                        <span class="link link-grey content__text-more">Читать полностью</span>#}
                        </div>
                    </div>
                    {% endif %}
                    {% if offer_filters|length %}
                    <div class="content__flist">
                        <h4>Свойства</h4>
                        {% for _, group in offer_filters.items() %}
                        {% if group['filters'] and group['filters']|length %}
                        <div class="content__flist-line">
                            <div class="content__flist-left">
                                {{ group['name'] }}
                            </div>
                            <ul class="content__flist-right">
                                {% for filter in group['filters'] %}
                                <li><a href="{{ url_for('site.catalog', path=filter.facete|generate_filter_url()) }}" class="link-normal link-grey">{{ filter.name }}</a></li>
                                {% endfor %}
                            </ul>
                        </div>
                        {% endif %}
                        {% endfor %}
                    </div>
                    {% endif %}
                    <div class="content__offer-shop">
                        <h4>Магазин</h4>
                        <a href="{{ redirect_link }}" class="link-normal" target="_blank">
                            <img data-src="{{ offer.shop.logotype }}" class="lazy" alt="{{ offer.shop.name }}" title="{{ offer.shop.name }}">
                        </a>
                    </div>
                    <div class="content__offer-share">
                        <h4>Поделиться</h4>
                        <script src="//yastatic.net/share2/share.js" async></script>
                        <div
                                class="ya-share2"
                                data-title="{{ altitle }} в магазине www.Botiloni.ru"
                                data-url="{{ request.url }}"
                                data-description="{{ altitle }} всего за {{ offer.price|pretty_price }} руб. и другие модели ботильонов в интернет-магазине www.Botiloni.ru."
                                data-image="{{ offer.picture_absolute_path }}"
                                data-services="collections,vkontakte,facebook,odnoklassniki,moimir{% if is_mobile %},viber,whatsapp{% endif %},telegram"
                        ></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="related">
            <h2>Похожие модели</h2>
            <ul class="offers offers--narrow">
                {% for offer in related_offers[:6] %}
                {{ render_offer(offer, shop=False) }}
                {% endfor %}
            </ul>
        </div>
        <div class="related">
            <h2>Рекомендуем</h2>
            <ul class="offers">
                {% for offer in related_offers[6:10] %}
                {{ render_offer(offer) }}
                {% endfor %}
            </ul>
        </div>
    </div>
    {{ render_share(with_script=False) }}
{% endblock %}